# Generated by Django 3.0.8 on 2020-07-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=8)),
                ('entryTime', models.DateTimeField(auto_now_add=True)),
                ('departureTime', models.DateTimeField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('In', models.BooleanField(default=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
